# Generated by Django 2.2.5 on 2021-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('total_course', models.PositiveIntegerField()),
                ('total_student', models.PositiveIntegerField()),
                ('link_university', models.CharField(max_length=100)),
            ],
        ),
    ]
